name: Pull Request to Production

on:
  push:
    branches:
      production


jobs:
  # Build out the changes to be pushed to the production repo, excluding the .git folder and CNAME file
  build-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Save the changes to be pushed as an artifact
    - name: Save changes
      uses: actions/upload-artifact@v3
      with:
        name: changes
        path: |
          ./
          !.git
          !CNAME
        retention-days: 1

  # Pull the changes from the build-changes job and push them to the production repo
  pull-request:
    needs: build-changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    # Checkout the production repo
    - name: Checkout remote
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        repository: smart-health-cards/smart-health-cards.github.io
        ref: gh-pages

    # Download the changes artifact from the build-changes job
    - name: Download changes
      uses: actions/download-artifact@v3
      with:
        name: changes
        path: changes

    # Commit the changes to the production repo
    - name: Commit changes
      run: |
        cp -r changes/* .
        rm -rf changes
        git config user.name '${{ github.event.head_commit.author.name }}'
        git config user.email '${{ github.event.head_commit.author.email }}'
        git add .
        git commit -m "${{ github.event.head_commit.message }}"
        git log --oneline -n 5

    # Push the changes to the production repo as a pull request
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ github.token }}
        branch: create-pull-request/br_pull-request
        branch-suffix: timestamp
        delete-branch: true
        signoff: true
        title: Ready for Production - ${{ github.event.head_commit.timestamp }}
        body: Automated pull request automatically generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
        labels: automated pr
        assignees: jmandel
